apiVersion: apps/v1
kind: Deployment
metadata:
  name: starrocks-controller
  namespace: starrocks
  labels:
    control-plane: starrocks-controller
spec:
  selector:
    matchLabels:
      control-plane: starrocks-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: starrocks-controller
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
        - command:
            - /sroperator
          args:
            - --leader-elect
          image: starrocks/operator:latest
          name: sroperator
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO: Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: starrocks-controller
      terminationGracePeriodSeconds: 10
