apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
  namespace: starrocks
  name: starrocks-cluster
spec:
  starRocksFeSpec:
    image: starrocks/fe-ubuntu:latest
    replicas: 3
    requests:
      cpu: 2
      memory: 1Gi
    service:
      type: LoadBalancer
  starRocksBeSpec:
    image: starrocks/be-ubuntu:latest
    replicas: 3
    requests:
      cpu: 2
      memory: 1Gi
